version: '3.8'
services:
  ratings:
    build: .
    ports:
      - "8080:8080"
    environment:
      SERVICE_VERSION: v2
      MONGO_DB_URL: mongodb://db:27017
      MONGO_DB_NAME: ratings
      MONGO_DB_USERNAME: ratings
      MONGO_DB_PASSWORD: ratings123
      MONGO_DB_AUTH_SOURCE: ratings
  db:
    image: bitnami/mongodb:latest
    volumes:
       - ./databases:/docker-entrypoint-initdb.d
    environment:
      MONGODB_ROOT_PASSWORD: rootpass
      MONGODB_USERNAME: ratings
      MONGODB_PASSWORD: ratings123
      MONGODB_DATABASE: ratings